# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steps', models.TextField()),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=255, unique=True)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='media')),
                ('ingredients', models.ManyToManyField(to='main.Ingredient')),
            ],
        ),
    ]
