# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
